"""Generate transcript.md — a clean, committed proof-of-run exercising every route
and every mandatory feature. Captures the structured observability log lines too.
"""
import io
import sys

sys.path.insert(0, "src")
import fitness_agents.observability as obs  # noqa: E402
from fitness_agents.hub import build_hub  # noqa: E402

# Capture observability events (instead of stderr) so we can show them inline.
_events: list[str] = []
_orig = obs.log_event


def _capture(kind, **fields):
    import json
    _events.append(json.dumps({"event": kind, **fields}, default=str))


# Patch every module that imported log_event by name.
import fitness_agents.router as r  # noqa: E402
import fitness_agents.tools as t  # noqa: E402
import fitness_agents.hub as h  # noqa: E402
import fitness_agents.agents.logger as lg  # noqa: E402
for mod in (obs, r, t, h, lg):
    mod.log_event = _capture

SCRIPT = [
    ("COACH", "What muscles does a deadlift work?"),
    ("WORKOUT_GENERATE", "Build me a 20 min upper body workout with dumbbells"),
    ("WORKOUT_LOG", "I just did 3x10 bench press at 185 lbs"),
    ("CLARIFY (ambiguous)", "Bench press"),
    ("WORKOUT_GENERATE + injury avoidance (#10)",
     "My right shoulder is injured — give me a 15 min workout I can do safely"),
    ("WORKOUT_GENERATE + multi-turn memory (#9)",
     "Actually make that session 25 minutes and focus on legs"),
    ("WORKOUT_LOG + fuzzy miss (graceful, no hallucinated match)",
     "Log this for me: I just did 4 sets of 12 zoolander curls at 50 lbs"),
]

hub = build_hub(with_memory=True)
cfg = {"configurable": {"thread_id": "transcript-session"}}

out = io.StringIO()
out.write("# Demo Transcript\n\n")
out.write("Generated by `python _gen_transcript.py`. One persistent thread is used "
          "across all turns, so the system has multi-turn memory (#9). The JSON lines "
          "are the structured observability log (#12) emitted during each turn.\n\n")

for label, user_input in SCRIPT:
    _events.clear()
    result = hub.invoke({"user_input": user_input, "messages": []}, cfg)
    decision = result.get("decision")
    response = result.get("response", "")
    out.write(f"## {label}\n\n")
    out.write(f"**User:** {user_input}\n\n")
    if decision:
        out.write(f"**Router:** `{decision.route}` (confidence "
                  f"{decision.confidence:.2f}) — {decision.reasoning}\n\n")
    out.write(f"**Assistant:**\n\n{response}\n\n")
    if _events:
        out.write("<details><summary>observability log</summary>\n\n```json\n")
        out.write("\n".join(_events))
        out.write("\n```\n\n</details>\n\n")
    out.write("---\n\n")

with open("transcript.md", "w", encoding="utf-8") as fh:
    fh.write(out.getvalue())
print("wrote transcript.md")
